# Generated by Django 2.2.6 on 2019-10-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=8.0)),
                ('amount_of_pizzas', models.IntegerField(default=1)),
                ('pizza_size', models.IntegerField(default=8)),
                ('pizza', models.CharField(max_length=12)),
                ('toppings', models.ManyToManyField(to='polls.Topping')),
            ],
        ),
    ]
