# Generated by Django 2.2.6 on 2019-10-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pizza_topping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
